[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "db>=0.1.1",
    "helpers>=0.2.0",
    "replit>=4.1.2",
    "requests>=2.32.4",
]
